support hostport filed for kafka
falcosecurity/charts pull request #194
Opened 2021-02-19 16:36 UTC by mrtc0

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

> /kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area falco-chart

> /area falco-exporter-chart

/area falcosidekick-chart

**What this PR does / why we need it**:

Kafka output settings work with `Kafka.HostPort` instead of `Kafka.URL` .  
This PR works by merging https://github.com/falcosecurity/falcosidekick/pull/194 .

**Which issue(s) this PR fixes**:

https://github.com/falcosecurity/falcosidekick/pull/194

Fixes #

**Special notes for your reviewer**:

**Checklist**

- [ ] Chart Version bumped
- [x] Variables are documented in the README.md
- [ ] CHANGELOG.md updated

2021-02-19 16:36 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/charts/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [fb6b00a](https://github.com/falcosecurity/charts/commits/fb6b00a452ab69ce5667eed1d4386e6adb616a65) support hostport filed for kafka
- [921d602](https://github.com/falcosecurity/charts/commits/921d60267656910869139fd71ea1f95c3d07fd1f) update README.md

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-02-19 16:36 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **cpanato** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @cpanato` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Fcharts).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/charts/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["cpanato"]} -->

2021-02-19 16:36 UTC, poiana commented
Welcome @mrtc0! It looks like this is your first PR to falcosecurity/charts 🎉

2021-02-19 17:09 UTC, Issif reviewed
You need to bump up the chart version and update the changelog please

2021-02-20 02:06 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/charts/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [fb6b00a](https://github.com/falcosecurity/charts/commits/fb6b00a452ab69ce5667eed1d4386e6adb616a65) support hostport filed for kafka
- [921d602](https://github.com/falcosecurity/charts/commits/921d60267656910869139fd71ea1f95c3d07fd1f) update README.md
- [ce7227d](https://github.com/falcosecurity/charts/commits/ce7227d919d94d3fd4d1ab3b1cb6ac65d96e6153) Merge branch 'master' of ssh://github.com/mrtc0/charts-1

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-02-20 02:06 UTC, poiana commented
@mrtc0: Adding label `do-not-merge/contains-merge-commits` because PR contains merge commits, which are not allowed in this repository.
Use `git rebase` to reapply your commits on top of the target branch. Detailed instructions for doing so can be found [here](https://git.k8s.io/community/contributors/guide/github-workflow.md#4-keep-your-branch-in-sync).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-02-20 02:11 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/charts/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [92ee6f1](https://github.com/falcosecurity/charts/commits/92ee6f1c5b794a28083f4c30809b3e8d9c87aac1) support hostport filed for kafka

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-02-20 12:01 UTC, Issif requested changes

2021-02-20 12:01 UTC, Issif commented on falcosidekick/CHANGELOG.md
> +* FIxed to specify `kafka.hostPort` insted of `kafka.url`
```suggestion
* FIxed to specify `kafka.hostPort` instead of `kafka.url`
```

2021-02-20 12:02 UTC, Issif commented
You need to signoff you commit please 🙏

2021-02-20 13:31 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **issif** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @issif` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Fcharts).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/charts/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["issif"]} -->

2021-02-20 13:32 UTC, mrtc0 commented on falcosidekick/CHANGELOG.md
> +* FIxed to specify `kafka.hostPort` insted of `kafka.url`
Sorry, I fixed it.

2021-02-20 13:54 UTC, Issif approved these changes
it's ok now, thanks.

can you create a PR for bumping up the dependency in falco chart, please https://github.com/falcosecurity/charts/blob/e75e690537b665f2da42da0cbb88ab8329f1821e/falco/Chart.yaml#L22

2021-02-20 13:54 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: 33e56871f6d0c27d85ba716c0bd4f0c050d7be6f</details>

2021-02-20 13:54 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/charts/pull/194#pullrequestreview-594754201" title="Approved">Issif</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Fcharts).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/charts/blob/master/OWNERS)~~ [Issif]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-02-20 13:57 UTC, merged