prepare v2.24.0 for falcosidekick
falcosecurity/charts pull request #269
Opened 2021-08-16 10:00 UTC by developer-guy

**What type of PR is this?**

/kind documentation

/kind feature

/kind chart-release

**Any specific area of the project related to this PR?**

/area falcosidekick-chart

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Checklist**

- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] CHANGELOG.md updated

2021-08-16 10:00 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/charts/pull/269#" title="Author self-approved">developer-guy</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **issif** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @issif` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Fcharts).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/charts/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["issif"]} -->

2021-08-16 16:24 UTC, Issif requested changes

2021-08-16 16:24 UTC, Issif commented on falcosidekick/templates/secrets.yaml
> +  GRAFANA_ALLFIELDSASTAGS: "{{ .Values.config.grafana.panelid | printf "%t" | b64enc}}"
```suggestion
  GRAFANA_ALLFIELDSASTAGS: "{{ .Values.config.grafana.allfieldsastags | printf "%t" | b64enc}}"
```

2021-08-16 16:24 UTC, Issif commented on falcosidekick/templates/secrets.yaml
> +  GRAFANA_PANELID: "{{ .Values.config.grafana.panelid | b64enc}}"
```suggestion
  GRAFANA_DASHBOARDID: "{{ .Values.config.grafana.dashboardid | toString | b64enc}}"
  GRAFANA_PANELID: "{{ .Values.config.grafana.panelid | toString | b64enc}}"
```

2021-08-16 16:24 UTC, Issif commented on falcosidekick/values.yaml
> +    minimumpriority: ""  # minimum priority of event for using this output, order is emergency|alert|critical|erro
```suggestion
    s3:
      endpoint: ""  # yandex storage endpoint (default: https://storage.yandexcloud.net) 
      bucket: "falcosidekick"  # Yandex storage, bucket name
      prefix: ""  # name of prefix, keys will have format: s3://<bucket>/<prefix>/YYYY-MM-DD/YYYY-MM-DDTHH:mm:ss.s+01:00.json
      minimumpriority: ""  # minimum priority of event for using this output, order is emergency|alert|critical|erro
```

2021-08-17 05:55 UTC, developer-guy commented on falcosidekick/templates/secrets.yaml
> +  GRAFANA_ALLFIELDSASTAGS: "{{ .Values.config.grafana.panelid | printf "%t" | b64enc}}"
thank you so much !!!

2021-08-17 05:55 UTC, developer-guy commented on falcosidekick/templates/secrets.yaml
> +  GRAFANA_PANELID: "{{ .Values.config.grafana.panelid | b64enc}}"
thank you so much !!!

2021-08-17 05:55 UTC, developer-guy commented on falcosidekick/values.yaml
> +    minimumpriority: ""  # minimum priority of event for using this output, order is emergency|alert|critical|erro
thank you so much !!!

2021-08-17 08:05 UTC, Issif requested changes
You forgot to complete the table with all values in README 🙏

2021-08-17 08:05 UTC, Issif commented on falcosidekick/CHANGELOG.md
> +* New output: Kafka REST (PR#263 thanks to @dirien)
```suggestion
* Add `Grafana` output
* Add `Fission` output
* Add `Yandex Cloud S3` output
* Add `Kafka REST` output
```

2021-08-17 08:05 UTC, Issif commented on falcosidekick/CHANGELOG.md
> +* Docker image is now available on AWS ECR Public Gallery (PR#265 thanks to @maxgio92)
```suggestion
* Docker image is now available on AWS ECR Public Gallery (`--set image.registry=public.ecr.aws`
```

2021-08-17 08:06 UTC, Issif commented on falcosidekick/Chart.yaml
>  description: A simple daemon to help you with falco's outputs
```suggestion
description: Connect Falco to your ecosystem
```

I prefer this description now

2021-08-17 13:21 UTC, developer-guy commented on falcosidekick/Chart.yaml
>  description: A simple daemon to help you with falco's outputs
fixed

2021-08-17 13:21 UTC, developer-guy commented on falcosidekick/CHANGELOG.md
> +* Docker image is now available on AWS ECR Public Gallery (PR#265 thanks to @maxgio92)
fixed

2021-08-17 13:21 UTC, developer-guy commented on falcosidekick/CHANGELOG.md
> +* New output: Kafka REST (PR#263 thanks to @dirien)
fixed

2021-08-17 13:22 UTC, Issif requested changes

2021-08-17 13:22 UTC, Issif commented on falcosidekick/CHANGELOG.md
> +* Docker image is now available on AWS ECR Public Gallery (`--set image.registry=public.ecr.aws`
```suggestion
* Docker image is now available on AWS ECR Public Gallery (`--set image.registry=public.ecr.aws`)
```

2021-08-17 13:53 UTC, developer-guy commented on falcosidekick/CHANGELOG.md
> +* Docker image is now available on AWS ECR Public Gallery (`--set image.registry=public.ecr.aws`
fix

2021-08-18 07:12 UTC, Issif commented on falcosidekick/README.md
> +| `config.wavefront.endpointhost`   | Wavefront endpßßßßoint address (only the host). If not empty, with endpointhost, Wavefront output is enabled
```suggestion
| `config.wavefront.endpointhost`   | Wavefront endpoint address (only the host). If not empty, with endpointhost, Wavefront output is enabled
```

2021-08-18 08:11 UTC, developer-guy commented on falcosidekick/README.md
> +| `config.wavefront.endpointhost`   | Wavefront endpßßßßoint address (only the host). If not empty, with endpointhost, Wavefront output is enabled
🤦🏻‍♂️ fixed

2021-08-18 21:01 UTC, Issif approved these changes

2021-08-18 21:01 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: 1379d8e5611256596988d5c5ac989222004a19d1</details>

2021-08-18 21:01 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/charts/pull/269#" title="Author self-approved">developer-guy</a>*, *<a href="https://github.com/falcosecurity/charts/pull/269#pullrequestreview-733348194" title="Approved">Issif</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Fcharts).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/charts/blob/master/OWNERS)~~ [Issif]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-08-18 21:02 UTC, merged