Filter out easy alerts and updated the Falco_rules
falcosecurity/charts pull request #321
Opened 2022-04-19 16:27 UTC by raviranjanelastisys

Signed-off-by: Ravi Ranjan <ravi.ranjan@elastisys.com>

**What type of PR is this?**

 /kind feature

**Any specific area of the project related to this PR?**

 /area falco-chart

**What this PR does / why we need it**:

Bases on our investigations and finding , updated the rules to `write_etc_common` , `Launch Package Management Process in Container` , `falco_privileged_images` & `falco_sensitive_mount_containers`.

**Which issue(s) this PR fixes**:
N/A

Fixes #

**Special notes for your reviewer**:

This issue consists in filtering a few "obvious" false-positives.
Updated the rules to `write_etc_common` , `Launch Package Management Process in Container` , `falco_privileged_images` & `falco_sensitive_mount_containers`.

**Checklist**

- [X] Chart Version bumped
- [ ] Variables are documented in the README.md
- [X] CHANGELOG.md updated

2022-04-19 16:27 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/charts/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [aa3c96c](https://github.com/falcosecurity/charts/commits/aa3c96cfe7ba17b7d5d1076bf54dd34d8da43542) Filter out easy alerts and updated the falco_rules

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2022-04-19 16:27 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/charts/pull/321#" title="Author self-approved">raviranjanelastisys</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **bencer** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @bencer` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Fcharts).

<details open>
Needs approval from an approver in each of these files:

- **[falco/OWNERS](https://github.com/falcosecurity/charts/blob/master/falco/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["bencer"]} -->

2022-04-19 16:30 UTC, raviranjanelastisys commented
/assign @bencer

2022-04-19 18:15 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/charts/pull/321#" title="Author self-approved">raviranjanelastisys</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **bencer** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Fcharts).

<details open>
Needs approval from an approver in each of these files:

- **[falco/OWNERS](https://github.com/falcosecurity/charts/blob/master/falco/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["bencer"]} -->

2022-04-20 08:29 UTC, cristiklein requested changes
Please fix the minor issue I raised. Otherwise looks good to me.

2022-04-20 08:29 UTC, poiana commented
@cristiklein: changing LGTM is restricted to collaborators

<details>

In response to [this](https://github.com/falcosecurity/charts/pull/321#pullrequestreview-946782856):

>Please fix the minor issue I raised. Otherwise looks good to me.


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-04-20 08:56 UTC, raviranjanelastisys commented on falco/rules/falco_rules.yaml
> +  condition: (proc.pname=postgres and proc.cmdline startswith "sh -c envdir \"/run/etc/wal-e.d/env\" wal-g wal-push")
@cristiklein Thanks Cristian !! As suggested , this is already opened PR in this commit - 
https://github.com/falcosecurity/charts/pull/319/files#diff-9e83f5b3c5b980da0d38329ea563be1e28722c0f04da90000bd19f3f6160cb97R1470

2022-04-20 09:12 UTC, raviranjanelastisys commented on falco/rules/falco_rules.yaml
> +  condition: (proc.pname=postgres and proc.cmdline startswith "sh -c envdir \"/run/etc/wal-e.d/env\" wal-g wal-push")
@cristiklein Is that you suggest ?

`condition: (proc.pname=postgres and proc.cmdline startswith "sh -c envdir /etc/wal-e.d/env /usr/local/bin/wal-e") or (proc.pname=postgres and proc.cmdline startswith "sh -c envdir \"/run/etc/wal-e.d/env\" wal-g wal-push")`  ??

2022-04-20 09:57 UTC, cristiklein commented on falco/rules/falco_rules.yaml
> +  condition: (proc.pname=postgres and proc.cmdline startswith "sh -c envdir \"/run/etc/wal-e.d/env\" wal-g wal-push")
Exactly! Maybe with a few strategic newlines to make it more readable. :smile:

2022-04-20 14:52 UTC, raviranjanelastisys commented on falco/rules/falco_rules.yaml
> +  condition: (proc.pname=postgres and proc.cmdline startswith "sh -c envdir \"/run/etc/wal-e.d/env\" wal-g wal-push")
@cristiklein Thanks I have done the changes in the readable format .

`condition: ((proc.pname=postgres and proc.cmdline startswith "sh -c envdir /etc/wal-e.d/env /usr/local/bin/wal-e") or
                   (proc.pname=postgres and proc.cmdline startswith "sh -c envdir \"/run/etc/wal-e.d/env\" wal-g wal-push"))`

2022-04-21 17:20 UTC, leogr requested changes
Hey @raviranjanelastisys 

You should propose changes to rules directly in the [falco repository](https://github.com/falcosecurity/falco/tree/master/rules).

The chart just uses a copy of those files, so we cannot modify them here.

Feel free to ping me if you need any help.

cc @cristiklein

2022-04-21 17:30 UTC, raviranjanelastisys commented
> so we cannot modify them here.

Thanks @leogr  !! I will opened PR in the suggested repository soon and let you know :) ...

2022-04-22 09:10 UTC, leogr commented
> > so we cannot modify them here.
> 
> Thanks @leogr !! I will opened PR in the suggested repository soon and let you know :) ...

Great, thank you! We really appreciate your contribution :+1: 

So I'm closing this PR in favor of the one you will open in the falco repository.

/close

2022-04-22 09:10 UTC, closed without merging

2022-04-22 09:10 UTC, poiana commented
@leogr: Closed this PR.

<details>

In response to [this](https://github.com/falcosecurity/charts/pull/321#issuecomment-1106222475):

>> > so we cannot modify them here.
>> 
>> Thanks @leogr !! I will opened PR in the suggested repository soon and let you know :) ...
>
>Great, thank you! We really appreciate your contribution :+1: 
>
>So I'm closing this PR in favor of the one you will open in the falco repository.
>
>/close
>
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-04-25 07:50 UTC, raviranjanelastisys commented
Opened the PR against the correct repos as suggested - https://github.com/falcosecurity/falco/pull/1981