feat(external-webui-redis): Add the possibility to use an external Redis Database
falcosecurity/charts pull request #357
Opened 2022-06-24 14:12 UTC by Lowaiz

Signed-off-by: Lyonel Martinez <lyonel.martinez@numberly.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

> /kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area falco-chart

> /area falco-exporter-chart

> /area falcosidekick-chart

**What this PR does / why we need it**:

Add the options to use an external database for the webui.
Now the Redis' values have an `enabled` member and the Webui's values have an `externalRedis` member, containing an `enabled`, an `url` and a `port` member.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Checklist**

- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] CHANGELOG.md updated

2022-06-24 14:12 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/charts/pull/357#" title="Author self-approved">Lowaiz</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **leodido** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @leodido` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Fcharts).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/charts/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leodido"]} -->

2022-06-24 14:12 UTC, poiana commented
Welcome @Lowaiz! It looks like this is your first PR to falcosecurity/charts 🎉

2022-06-26 19:45 UTC, Issif commented
Thanks. I will review in details asap. Can you just add in the descriptions of settings that the redis must have the redissearch module enabled, it's a requirement. Thanks

2022-06-27 09:38 UTC, Issif requested changes
I'm thinking we could simplify a little the UX by removing the `webui.externalRedis.enabled` and `webui.redis.enabled`.
The conditions could be only:
- if `webui.externalRedis.url != ""` then disable the local redis

wdyt?

2022-06-27 09:38 UTC, Issif commented on falcosidekick/CHANGELOG.md
>  ## 0.5.3
```suggestion
## 0.5.4
```
I forgot to change this version number after my last copy paste. Can you update it for me please.

2022-06-27 09:38 UTC, Issif commented on falcosidekick/templates/deployment-ui.yaml
> +            - "{{ required "External Redis is enable. Please set the URL to the database." .Values.webui.externalRedis.url }}:{{ .Values.webui.externalRedis.port | default "6379" }}"
```suggestion
            - "{{ required "External Redis is enabled. Please set the URL to the database." .Values.webui.externalRedis.url }}:{{ .Values.webui.externalRedis.port | default "6379" }}"
```

2022-06-27 12:08 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/charts/pull/357#" title="Author self-approved">Lowaiz</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **issif** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Fcharts).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/charts/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["issif"]} -->

2022-06-27 14:14 UTC, Lowaiz commented
> I just think we need a way to make them exclusive
An exclusive test now is done in the beginning of the deployment-ui file.

2022-06-30 09:41 UTC, Issif requested changes

2022-06-30 09:41 UTC, Issif commented on falcosidekick/templates/deployment-ui.yaml
> +  {{ fail "Both webui.redis and webui.externalRedis modules are enabled. Please unset one them." }}
```suggestion
  {{ fail "Both webui.redis and webui.externalRedis modules are enabled. Please disable one of them." }}
```

2022-06-30 10:15 UTC, Issif approved these changes

2022-06-30 10:15 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/charts/pull/357#pullrequestreview-1024621451" title="Approved">Issif</a>*, *<a href="https://github.com/falcosecurity/charts/pull/357#" title="Author self-approved">Lowaiz</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Fcharts).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/charts/blob/master/OWNERS)~~ [Issif]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-06-30 10:15 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: 6317604b72ff0a89c1c7975cc14ab2521b96f759</details>

2022-06-30 10:16 UTC, merged