cleanup(OWNERS): remove inactive approvers
falcosecurity/charts pull request #360
Opened 2022-07-05 15:29 UTC by jasondellaluce

**What type of PR is this?**

/kind cleanup

/kind documentation

**Any specific area of the project related to this PR?**

**What this PR does / why we need it**:

For https://github.com/falcosecurity/falco/issues/2115, this PR moves inactive approvers (who had very little or zero contributions over the past 6 months) from `approvers` to `emeritus_approvers` in OWNERS.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

2022-07-05 15:29 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/charts/pull/360#" title="Author self-approved">jasondellaluce</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **leogr** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @leogr` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Fcharts).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/charts/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leogr"]} -->

2022-07-05 15:30 UTC, cpanato commented on falco/OWNERS
> +- nestorsalceda
nit: new line

2022-07-05 15:31 UTC, cpanato commented
and will need to bump the chart version, then i recommend to split in two prs for each chart

2022-07-05 15:31 UTC, cpanato commented
ops, sorry pressed the wrong button

2022-07-06 10:33 UTC, fntlnz requested changes
Please restore `fntlnz` https://github.com/falcosecurity/falco/issues/2115#issuecomment-1176045086

2022-07-15 10:28 UTC, jasondellaluce commented
> and will need to bump the chart version, then i recommend to split in two prs for each chart

@cpanato I think you have a good point here, specially considering that the Falco chart has been recently released and deeply refactored. I'm gonna close this PR and split the OWNERS review in two.

2022-07-15 10:29 UTC, closed without merging