feat: updated grafana dashboard
falcosecurity/charts pull request #657
Opened 2024-04-17 21:14 UTC by dotdc

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

/kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area falco-exporter-chart

**What this PR does / why we need it**:

Updated the Falco Grafana dashboard ito make it more user friendly and removed deprecated panels since Grafana 7 (2020).
All details in https://github.com/falcosecurity/charts/issues/656

**Which issue(s) this PR fixes**:

Fixes #656

**Special notes for your reviewer**:

**Checklist**

- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] CHANGELOG.md updated

2024-04-17 21:14 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/charts/pull/657#" title="Author self-approved">dotdc</a>*
**Once this PR has been reviewed and has the lgtm label**, please assign cpanato for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Fcharts).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/charts/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["cpanato"]} -->

2024-04-26 12:54 UTC, Issif requested changes
The dashboard seems good to me, I just can't explain we have commentary in some of the expressions. See my comments. Once removed, I'll approve it.

2024-04-26 12:54 UTC, Issif commented on charts/falco-exporter/templates/grafana-dashboard.yaml
> +                "expr": "sum(rate(falco_events[$__rate_interval])) by (pod, hostname)\n# {container=\"falco-exporter\", endpoint=\"metrics\", hostname=\"falco-27jks\", instance=\"10.0.0.5:9376\", job
```suggestion
                "expr": "sum(rate(falco_events[$__rate_interval])) by (pod, hostname)",
```

2024-04-26 19:12 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/charts/pull/657#" title="Author self-approved">dotdc</a>*
**Once this PR has been reviewed and has the lgtm label**, please ask for approval from issif. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Fcharts).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/charts/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["issif"]} -->

2024-04-26 19:18 UTC, dotdc commented
> The dashboard seems good to me, I just can't explain we have commentary in some of the expressions. See my comments. Once removed, I'll approve it.

Yes, this was debug data, should be all good now.

2024-04-30 08:52 UTC, Issif submitted a review, later dismissed

2024-04-30 08:52 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: f3044fdc7114451dbb3afe7c8122f43fe376ce16</details>

2024-04-30 08:52 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/charts/pull/657#" title="Author self-approved">dotdc</a>*, *<a href="https://github.com/falcosecurity/charts/pull/657#pullrequestreview-2030671744" title="Approved">Issif</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Fcharts).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/charts/blob/master/OWNERS)~~ [Issif]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2024-04-30 11:05 UTC, poiana commented
New changes are detected. LGTM label has been removed.

2024-04-30 11:05 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/charts/pull/657#" title="Author self-approved">dotdc</a>*, *<a href="https://github.com/falcosecurity/charts/pull/657#pullrequestreview-2030671744" title="Approved">Issif</a>*


The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Fcharts).

<details open>
Needs approval from an approver in each of these files:


Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2024-04-30 12:13 UTC, Issif approved these changes

2024-04-30 12:13 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/charts/pull/657#" title="Author self-approved">dotdc</a>*, *<a href="https://github.com/falcosecurity/charts/pull/657#pullrequestreview-2031142058" title="Approved">Issif</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Fcharts).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/charts/blob/master/OWNERS)~~ [Issif]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2024-04-30 12:13 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: 54d99ae8e036c271237757cd44f80578a16eea12</details>

2024-04-30 12:13 UTC, merged