fix: use roles_files.
falcosecurity/charts pull request #781
Opened 2024-11-19 14:30 UTC by jcchavezs

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If this PR will release a new chart version please make sure to also uncomment the following line:

> /kind chart-release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area falco-chart

> /area falco-exporter-chart

> /area falcosidekick-chart

> /area falco-talon

> /area event-generator-chart

> /area k8s-metacollector

**What this PR does / why we need it**:

Although rules_file has been removed, it is still being referenced.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Checklist**

- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] CHANGELOG.md updated

2024-11-19 14:30 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/.github/blob/main/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [8995d04](https://github.com/falcosecurity/charts/commits/8995d040e1779c7823057abfffaec90aeee688e0) fix: use roles_files.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2024-11-19 14:30 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/charts/pull/781#" title="Author self-approved">jcchavezs</a>*
**Once this PR has been reviewed and has the lgtm label**, please assign [leogr](https://github.com/leogr) for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Fcharts).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/charts/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leogr"]} -->

2024-11-19 14:39 UTC, Issif commented
Hi,

To be valid, your PR needs:
- signed off commits
- an update of the chart version (in CHART.yaml)
- an update of the readme (run: `make docs-falco`)
- an update of the changelog

Thanks

2024-12-20 10:59 UTC, leogr requested changes
First of all, thank you for this PR event; we can't merge it due to the issues explained above.

Furthermore, https://github.com/falcosecurity/charts/pull/720 already fixed this, except for:

- [the test config](https://github.com/falcosecurity/charts/blob/master/tests/falco-test-ci.yaml#L40)

I recommend closing this PR and opening a new one just for the test file.

2025-03-20 16:14 UTC, poiana commented
Issues go stale after 90d of inactivity.

Mark the issue as fresh with `/remove-lifecycle stale`.

Stale issues rot after an additional 30d of inactivity and eventually close.

If this issue is safe to close now please do so with `/close`.

Provide feedback via https://github.com/falcosecurity/community.

/lifecycle stale

2025-04-19 16:15 UTC, poiana commented
Stale issues rot after 30d of inactivity.

Mark the issue as fresh with `/remove-lifecycle rotten`.

Rotten issues close after an additional 30d of inactivity.

If this issue is safe to close now please do so with `/close`.

Provide feedback via https://github.com/falcosecurity/community.

/lifecycle rotten

2025-05-19 16:16 UTC, closed without merging

2025-05-19 16:16 UTC, poiana commented
@poiana: Closed this PR.

<details>

In response to [this](https://github.com/falcosecurity/charts/pull/781#issuecomment-2891586137):

>Rotten issues close after 30d of inactivity.
>
>Reopen the issue with `/reopen`.
>
>Mark the issue as fresh with `/remove-lifecycle rotten`.
>
>Provide feedback via https://github.com/falcosecurity/community.
>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository.
</details>